import Head from 'next/head'

export const getStaticPaths = async () => {
  const res = await fetch('https://newsapi.org/v2/top-headlines?country=id&apiKey=f11ad12345f6462a82aa2c6499251dfa');
  const data = await res.json();

  const paths = data.articles.map(berita => {
    return {
      params: { id: berita.title }
    }
  })

  return {
    paths,
    fallback: false
  }
}

export const getStaticProps = async (context) => {
  const id = context.params.id;
  const res = await fetch('https://newsapi.org/v2/top-headlines?country=id&apiKey=f11ad12345f6462a82aa2c6499251dfa/' + id);
  const data = await res.json()

  return {
    props: { porosBerita: data }
  }
}

const BeritaContent = ({ porosBerita }) => {
  return (
    <section>
      <Head>
        <title>Berita | POROS Organization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{porosBerita.id}</h1>
    </section>
  );
}
export default BeritaContent;