import Head from 'next/head'
import styles from '../../styles/Home.module.css'

// export const getStaticPaths = async () => {
//   const res = await fetch('https://newsapi.org/v2/top-headlines?country=id&apiKey=f11ad12345f6462a82aa2c6499251dfa');
//   const data = await res.json();

//   const paths = data.articles.map(berita => {
//     return {
//       params: { id: berita.title }
//     }
//   })

//   return {
//     paths,
//     fallback: false
//   }
// }

// export const getStaticProps = async (context) => {
//   const id = context.params.id;
//   const res = await fetch('https://newsapi.org/v2/top-headlines?country=id&apiKey=f11ad12345f6462a82aa2c6499251dfa/' + id);
//   const data = await res.json()

//   return {
//     props: { porosBerita: data }
//   }
// }

const BeritaContent = () => {
  return (
    <>
      <Head>
        <title>Berita | POROS Organization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* LIST TODO */}
      {/* - TITLE
          - PUBLISH AT WHEN
          - DESCRIPTION
          - IMAGE
          - CONTENT */}

      {/* Start here */}
      <section className='font-monts'>
        <div className={styles.porosBerita__header_frame}>
          <div className={styles.porosBerita__header_background}>
            <p className={styles.porosBerita__header_title}>FOSS</p>
          </div>
        </div>
        {/* <h1 className={`text-red-500 ${styles.porosBerita__header_title}`}> Halo </h1> */}
      </section>
    </>
  );
}
export default BeritaContent;