import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export const getStaticProps = async () => {
  const res = await fetch('https://newsapi.org/v2/top-headlines?country=id&apiKey=f11ad12345f6462a82aa2c6499251dfa');
  const data = await res.json();

  return {
    props: { porosBerita: data }
  }
}


export default function Berita({ porosBerita }) {
  return (
    <>
      <Head>
        <title>Berita | POROS Organization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div>
          {porosBerita.articles.map(berita => (
            <div key={berita.id}>
              <h1>{berita.author}</h1>
            </div>
          ))}
        </div>
      </section>
    </>
  )
}