import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>POROS Organization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>home</h1>
    </>
  )
}
